//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

// Package config provides terminal output for the
// configuration management commands (ctx config).
//
// # Exported Functions
//
// [ProfileStatus] prints the active runtime profile
// status line. It distinguishes between "dev" mode,
// "base" mode, and no profile (with a hint to create
// a .ctxrc file).
//
// [Schema] prints the raw JSON schema content for the
// ctx configuration file. The schema is printed as-is
// without additional formatting.
//
// [SwitchConfirm] prints the confirmation message
// after a profile switch operation completes. The
// message is generated by the switch logic and passed
// through verbatim.
//
// # Message Categories
//
//   - Info: profile status, schema dump, switch
//     confirmation
//
// # Nil Safety
//
// All functions treat a nil *cobra.Command as a no-op.
package config
