version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - gosec
    - unconvert
    - gocritic

  settings:
    govet:
      enable:
        - shadow

  exclusions:
    paths:
      - vendor
      - dist
      - site

run:
  timeout: 5m

output:
  formats:
    text:
      colors: true
