//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

// Package archive creates **compressed tar archives** of ctx
// state for the `ctx backup` family of commands — bundling
// `.context/`, `.claude/`, `ideas/`, and (optionally) the
// global `~/.claude/` directory into a timestamped `.tar.gz`
// for off-machine storage on an SMB share or local disk.
//
// The package is the engine. The user-facing knobs
// (`--scope project|global|all`, `--no-smb`, etc.) live in
// `internal/cli/backup`.
//
// # Public Surface
//
//   - **[Create](outPath, entries)** — builds a tar.gz at
//     `outPath` containing every entry in `entries`.
//     Optional entries that resolve to a missing path
//     emit a diagnostic message but do not fail the
//     operation (a common case: `ideas/` may not exist
//     in fresh projects).
//   - **[BackupProject](contextDir, outDir)** — wraps
//     [Create] with the project-scope entry list:
//     `.context/`, `.claude/`, `ideas/`, `.bashrc`-like
//     project shell extensions.
//   - **[BackupGlobal](outDir)** — global scope:
//     `~/.claude/` minus `todos/` (excluded because
//     it can be huge and is regenerated by Claude Code).
//   - **[CheckSMBMountWarnings](url)** — sanity-checks
//     the configured SMB mount and warns about common
//     misconfigurations (mount path missing, write
//     permission missing, etc.).
//   - **[CheckBackupMarker](contextDir)** — reads the
//     last-backup timestamp marker so
//     `ctx system check-backup-age` can nudge the user.
//
// # Output Naming
//
// Archives are named `ctx-<scope>-YYYY-MM-DD-HHMMSS.tar.gz`
// for unambiguous chronological sorting in the destination
// directory.
//
// # Concurrency
//
// Filesystem-bound and stateless. Concurrent invocations
// against the same destination would compete for the same
// timestamped filename — single-process is the assumed
// model.
//
// # Related Packages
//
//   - [internal/cli/backup]                — the
//     `ctx backup` CLI surface.
//   - [internal/cli/system/cmd/check_backup_age] — the
//     hook that nudges when [CheckBackupMarker] reports
//     stale.
//   - [internal/config/archive]            — file-name
//     prefix and SMB env-var name constants.
package archive
