//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package tpl

import (
	"fmt"
	"testing"
)

// oldObsidianReadme is the pre-migration fmt.Sprintf format string,
// retained verbatim as the golden source. The migrated template
// (templates/obsidian-readme.md.tmpl) must reproduce its output
// byte-for-byte; this is the behavior-preserving contract.
const oldObsidianReadme = `# journal-obsidian (generated)

Generated by ` + "`ctx journal obsidian`" + `, read-only.
Do not edit files here - changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal obsidian
` + "```" + `

## Usage

Open this directory as an Obsidian vault:

1. Open Obsidian
2. Choose "Open folder as vault"
3. Select this directory
`

// TestTemplatesParse fails if any embedded template failed to parse at
// init — the CI guard that lets the migration avoid template.Must (and
// thus a panic) while still catching a malformed template.
func TestTemplatesParse(t *testing.T) {
	if len(parseErrs) > 0 {
		t.Fatalf("embedded templates failed to parse at init: %v", parseErrs)
	}
}

// TestObsidianReadmeMatchesLegacy proves the migrated template renders
// identically to the legacy fmt.Sprintf form.
func TestObsidianReadmeMatchesLegacy(t *testing.T) {
	const journalDir = "src/journal"
	want := fmt.Sprintf(oldObsidianReadme, journalDir)

	got, err := Render(ObsidianReadme, ObsidianData{JournalDir: journalDir})
	if err != nil {
		t.Fatalf("Render returned error: %v", err)
	}
	if got != want {
		t.Errorf(
			"ObsidianReadme render drift:\n--- want ---\n%q\n--- got ---\n%q",
			want, got,
		)
	}
}
