//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package tpl

import (
	"fmt"
	"testing"
	"text/template"
)

// The old* constants below are the pre-migration fmt.Sprintf format
// strings, kept verbatim as golden sources. Each migrated template
// must reproduce its legacy output byte-for-byte; that is the
// behavior-preserving contract this file enforces.

const oldObsidianReadme = `# journal-obsidian (generated)

Generated by ` + "`ctx journal obsidian`" + `, read-only.
Do not edit files here - changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal obsidian
` + "```" + `

## Usage

Open this directory as an Obsidian vault:

1. Open Obsidian
2. Choose "Open folder as vault"
3. Select this directory
`

const oldJournalSiteReadme = `# journal-site (generated)

This directory is generated by ` + "`ctx journal site`" + ` and is read-only.
Do not edit files here - changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal site          # generate
ctx journal site --serve  # generate and preview
` + "```" + `
`

const oldTriggerScript = `#!/usr/bin/env bash
# Trigger: %s
# Type:    %s
# Created by: ctx trigger add
#
# Enable with: ctx trigger enable %[1]s
# Test with:   ctx trigger test %[2]s

set -euo pipefail

# Read the JSON event payload from stdin.
INPUT=$(cat)

# Parse the fields you need from the payload.
TRIGGER_TYPE=$(echo "$INPUT" | jq -r '.hookType // empty')
TOOL=$(echo "$INPUT" | jq -r '.tool // empty')
PATH_ARG=$(echo "$INPUT" | jq -r '.path // empty')

# Your trigger logic here.

# Return a JSON response on stdout. "cancel": true blocks
# the tool call (pre-tool-use only); "context" injects
# additional context; "message" is shown to the user.
echo '{"cancel": false, "context": "", "message": ""}'
`

const oldLearning = `## [%s] %s

**Context**: %s

**Lesson**: %s

**Application**: %s
`

const oldDecision = `## [%s] %s

**Status**: Accepted

**Context**: %s

**Decision**: %s

**Rationale**: %s

**Consequence**: %s
`

// assertRenderMatches renders tmpl with data and fails if the output
// differs from want.
func assertRenderMatches(
	t *testing.T, tmpl *template.Template, data any, want string,
) {
	t.Helper()
	got, err := Render(tmpl, data)
	if err != nil {
		t.Fatalf("Render returned error: %v", err)
	}
	if got != want {
		t.Errorf(
			"render drift:\n--- want ---\n%q\n--- got ---\n%q", want, got,
		)
	}
}

// TestTemplatesParse fails if any embedded template failed to parse at
// init — the CI guard that lets the migration avoid template.Must (and
// thus a panic) while still catching a malformed template.
func TestTemplatesParse(t *testing.T) {
	if len(parseErrs) > 0 {
		t.Fatalf("embedded templates failed to parse at init: %v", parseErrs)
	}
}

func TestObsidianReadmeMatchesLegacy(t *testing.T) {
	const journalDir = "src/journal"
	assertRenderMatches(t, ObsidianReadme,
		ObsidianData{JournalDir: journalDir},
		fmt.Sprintf(oldObsidianReadme, journalDir))
}

func TestJournalSiteReadmeMatchesLegacy(t *testing.T) {
	const journalDir = "src/journal"
	assertRenderMatches(t, JournalSiteReadme,
		JournalSiteData{JournalDir: journalDir},
		fmt.Sprintf(oldJournalSiteReadme, journalDir))
}

func TestTriggerScriptMatchesLegacy(t *testing.T) {
	const name, hookType = "my-trigger", "pre-tool-use"
	assertRenderMatches(t, TriggerScript,
		TriggerData{Name: name, Type: hookType},
		fmt.Sprintf(oldTriggerScript, name, hookType))
}

func TestLearningMatchesLegacy(t *testing.T) {
	const ts, title, ctxt, lesson, app = "2026-05-30-120000", "T", "C", "L", "A"
	assertRenderMatches(t, Learning,
		LearningData{
			Timestamp: ts, Title: title, Context: ctxt,
			Lesson: lesson, Application: app,
		},
		fmt.Sprintf(oldLearning, ts, title, ctxt, lesson, app))
}

func TestDecisionMatchesLegacy(t *testing.T) {
	const ts, title, ctxt, rat, cons = "2026-05-30-120000", "T", "C", "R", "Q"
	assertRenderMatches(t, Decision,
		DecisionData{
			Timestamp: ts, Title: title, Context: ctxt,
			Rationale: rat, Consequence: cons,
		},
		fmt.Sprintf(oldDecision, ts, title, ctxt, title, rat, cons))
}
