//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

// Package load provides terminal output for the context
// load commands (ctx load, ctx agent).
//
// # Exported Functions
//
// [Raw] outputs context files without assembly or
// headers. Files are printed in read order separated
// by blank lines, with content printed as-is. This
// mode is used for piping context into other tools.
//
// [Assembled] outputs context as a formatted Markdown
// document with token budgeting. Files are included in
// read order until the token budget is exhausted. Each
// file gets a section heading generated by a caller-
// supplied title function. Truncated files are noted
// in the output with a separator and truncation notice.
// The document opens with a budget summary showing
// used vs. available tokens.
//
// # Message Categories
//
//   - Info: raw file content or assembled Markdown
//     document with budget metadata
//
// # Usage
//
//	if raw {
//	    load.Raw(cmd, files)
//	} else {
//	    load.Assembled(cmd, files, budget, total, titleFn)
//	}
package load
