[project]
site_name = "ctx: Session Journal"
site_description = "AI session history and notes"
site_author = "Jose Alekhinne <alekhinejose@gmail.com>"
site_url = "https://ctx.ist/"
repo_url = "https://github.com/ActiveMemory/ctx"
repo_name = "ActiveMemory/ctx"
copyright = """
Copyright &copy; 2026&ndash;present <a href="https://github.com/ActiveMemory/ctx/">Context contributors</a>.<br>
<a href="https://github.com/ActiveMemory/ctx"><code>ctx</code>'s code</a> is distributed under
<a href="https://github.com/ActiveMemory/ctx/blob/main/LICENSE"><strong>Apache (v2.0)</strong></a>.<br>
"""

